name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: backend
    - name: Build
      run: dotnet build --no-restore
      working-directory: backend
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: backend
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: NUnit Reporter
      # You may pin to the exact commit or the version.
      # uses: MirageNet/nunit-reporter@8abbab7fdac37ef57d1621a5cfa508cdf000428f
        uses: MirageNet/nunit-reporter@v1.0.5
        with:
          # github token
          access-token: 
          # glob to junit xml files
      path: 
      # max number of failed tests to include
      numFailures: # optional, default is 30
